HiperChat/WebChat/WebChat/Models/Contexto.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebChat.Models
{
    public class Contexto : DbContext
    {
        public Contexto(DbContextOptions<Contexto> options) : base(options)
        {
            Database.EnsureCreated();
        }

        public DbSet<RespostaChat> RespostaChat { get; set; }


    }
}

HiperChat/WebChat/WebChat/Models/ErrorViewModel.cs
using System;

namespace WebChat.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HiperChat/WebChat/WebChat/Models/RequestApi.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebChat.Models
{
    public class RequestApi
    {
        public string mensagem { get; set; }

    }
}

HiperChat/WebChat/WebChat/Models/ResponseApi.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebChat.Models
{
    public class ResponseApi
    {
        public string resposta { get; set; }
    }
}

HiperChat/WebChat/WebChat/Models/RespostaChat.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebChat.Models
{
    [Table("RespostaChat")]
    public class RespostaChat
    {
        [Column("Id")]
        [Display(Name = "Código")]
        public int Id { get; set; }

        [Column("Resposta")]
        [Display(Name = "Resposta")]
        public string Resposta { get; set; }

        [Column("Mensagem")]
        [Display(Name = "Mensagem")]
        public string Mensagem { get; set; }

    }
}

HiperChat/WebChat/WebChat/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebChat.Models;

namespace WebChat.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HiperChat/WebChat/WebChat/Controllers/RespostaChatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebChat.Models;

namespace WebChat.Controllers
{
    public class RespostaChatsController : Controller
    {
        private readonly Contexto _context;

        public RespostaChatsController(Contexto context)
        {
            _context = context;
        }

        // GET: RespostaChats
        public async Task<IActionResult> Index()
        {
            return View(await _context.RespostaChat.ToListAsync());
        }

        // GET: RespostaChats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var respostaChat = await _context.RespostaChat
                .FirstOrDefaultAsync(m => m.Id == id);
            if (respostaChat == null)
            {
                return NotFound();
            }

            return View(respostaChat);
        }

        // GET: RespostaChats/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RespostaChats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Resposta,Mensagem")] RespostaChat respostaChat)
        {
            if (ModelState.IsValid)
            {
                _context.Add(respostaChat);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(respostaChat);
        }

        // GET: RespostaChats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var respostaChat = await _context.RespostaChat.FindAsync(id);
            if (respostaChat == null)
            {
                return NotFound();
            }
            return View(respostaChat);
        }

        // POST: RespostaChats/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Resposta,Mensagem")] RespostaChat respostaChat)
        {
            if (id != respostaChat.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(respostaChat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RespostaChatExists(respostaChat.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(respostaChat);
        }

        // GET: RespostaChats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var respostaChat = await _context.RespostaChat
                .FirstOrDefaultAsync(m => m.Id == id);
            if (respostaChat == null)
            {
                return NotFound();
            }

            return View(respostaChat);
        }

        // POST: RespostaChats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var respostaChat = await _context.RespostaChat.FindAsync(id);
            _context.RespostaChat.Remove(respostaChat);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RespostaChatExists(int id)
        {
            return _context.RespostaChat.Any(e => e.Id == id);
        }


        [HttpPost("api/Chat")]
        public async Task<JsonResult> Chat(RequestApi request)
        {
            var respostaChat = await _context.RespostaChat.Where(m => m.Mensagem.ToUpper().Contains(request.mensagem.ToUpper())).FirstOrDefaultAsync();

            if (respostaChat != null)
            {
                var resposta = new ResponseApi { resposta = respostaChat.Resposta };

                return Json(resposta);
            }
            else
            {
                var resposta = new ResponseApi { resposta = "Não entendemos sua pergunta. Poderia reformular?" };
                return Json(resposta);
            }
        }


    }
}

HiperChat/WebChat/WebChat/Views/Home/Index.cshtml
<div class="container-logo">
     

</div>



<main class="conteudoPrincipal">
    <div class="container">
        <h2 class="subtitulo">Navegue pelas disponibilidades do Hiper</h2>

        <nav>
            <!--classe pai mudar aqui o flex box -->
            <ul class="conteudoPrincipal-Lista">
                <li class="conteudoPrincipal-Lista-link"><a href="https://ajuda.hiper.com.br/hc/pt-br/categories/203150927-Hiper-Gest%C3%A3o">Hiper Gestão</a></li>
                <li class="conteudoPrincipal-Lista-link"><a href="https://ajuda.hiper.com.br/hc/pt-br/categories/115000345352-Hiper-Loja">Hiper Loja</a></li>
                <li class="conteudoPrincipal-Lista-link"><a href="https://ajuda.hiper.com.br/hc/pt-br/categories/115000990708-Hiper-Caixa">Hiper Caixa</a></li>
                <li class="conteudoPrincipal-Lista-link"><a href="https://ajuda.hiper.com.br/hc/pt-br/categories/360001652452-Central-de-Artigos">Central de Artigos</a></li>
                <li class="conteudoPrincipal-Lista-link"><a href="https://ajuda.hiper.com.br/hc/pt-br/categories/360001651471-Central-de-Relat%C3%B3rios">Relatórios</a></li>
                <li class="conteudoPrincipal-Lista-link"><a href="https://ajuda.hiper.com.br/hc/pt-br/categories/360001652472-Central-de-V%C3%ADdeos">Videos</a></li>
                <li class="conteudoPrincipal-Lista-link"><a href="https://ajuda.hiper.com.br/hc/pt-br/categories/360001557631-Release-Notes">Release Note</a></li>
                <li class="conteudoPrincipal-Lista-link"><a href="https://ajuda.hiper.com.br/hc/pt-br/categories/360001352232-Base-de-Conhecimento">Base de Conhecimento</a></li>
                <li class="conteudoPrincipal-Lista-link"><a href="https://ajuda.hiper.com.br/hc/pt-br/categories/115000947668-Hiper-Windows">Hiper Windows (Legado)</a></li>
                <li class="conteudoPrincipal-Lista-link"><a href="https://ajuda.hiper.com.br/hc/pt-br/categories/115000990728-Hiper-Vendas">Hiper Vendas</a></li>
                <li class="conteudoPrincipal-Lista-link"><a href="https://ajuda.hiper.com.br/hc/pt-br/categories/115000025232-Portal-do-Hiperador">Hiperador</a></li>
                <li class="conteudoPrincipal-Lista-link"><a href="https://ajuda.hiper.com.br/hc/pt-br/categories/360000068551-Outras-informa%C3%A7%C3%B5es">Assuntos Gerais</a></li>

            </ul>
        </nav>
    </div>
</main>




<input type="checkbox" id="open_menu" />

<div id="container" class="abrir">

    <div id="imagemChat">
        <img id="logo" alt="logo" class="logo" src="~/css/hiper.png" />
    </div>
    <div id="displaymensagem"> </div>


    <div class="inputs">
        <input type="text"
               id="mensagem"
               placeholder="Escreva a sua mensagem" />
        <input id="Enviar" type="button" value="Enviar" />
    </div>

</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/js/API - chat.js"></script>
<script src="~/js/js - chat.js"></script>
<link href="~/css/Chat CSS.css" rel="stylesheet" />
<link href="~/css/AjudaGridcss.css" rel="stylesheet" />

HiperChat/WebChat/WebChat/Views/RespostaChats/Create.cshtml
@model WebChat.Models.RespostaChat

@{
    ViewData["Title"] = "Criar";
}

<h1>Criar Mensagens</h1>

<h4>Respostas Chat</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Resposta" class="control-label"></label>
                <input asp-for="Resposta" class="form-control" />
                <span asp-validation-for="Resposta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mensagem" class="control-label"></label>
                <input asp-for="Mensagem" class="form-control" />
                <span asp-validation-for="Mensagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar a lista de Mensagens</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HiperChat/WebChat/WebChat/Views/RespostaChats/Delete.cshtml
@model WebChat.Models.RespostaChat

@{
    ViewData["Title"] = "Apagar Mensagens";
}

<h1>Apagar</h1>

<h3>Você tem certeza que deseja apagar? :)</h3>
<div>
    <h4>Resposta Chats</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resposta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resposta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mensagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mensagem)
        </dd>
    </dl>
    
    <form asp-action="Apagar">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar a Lista</a>
    </form>
</div>

HiperChat/WebChat/WebChat/Views/RespostaChats/Details.cshtml
@model WebChat.Models.RespostaChat

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes</h1>

<div>
    <h4>Respostas Chat</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Resposta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Resposta)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Mensagem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Mensagem)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Voltar a Lista</a>
</div>

HiperChat/WebChat/WebChat/Views/RespostaChats/Edit.cshtml
@model WebChat.Models.RespostaChat

@{
    ViewData["Title"] = "Editar";
}

<h1>Editar</h1>

<h4>Respostas Chat</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Resposta" class="control-label"></label>
                <input asp-for="Resposta" class="form-control" />
                <span asp-validation-for="Resposta" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Mensagem" class="control-label"></label>
                <input asp-for="Mensagem" class="form-control" />
                <span asp-validation-for="Mensagem" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar a Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HiperChat/WebChat/WebChat/Views/RespostaChats/Index.cshtml
@model IEnumerable<WebChat.Models.RespostaChat>

@{
    ViewData["Title"] = "Dados Gerais das Mensagens";
}

<h1>Menu de edições</h1>

<p>
    <a asp-action="Create">Adicionar nova mensagem</a>
</p>

<input type="text" name="Buscar" id="buscaMSG" 
placeholder = "Digite uma palavra-chave" />
<button id="btn"> <b><font color="black" size="3">Filtrar</font></b></button>



<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Resposta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Mensagem)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Resposta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mensagem)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Apagar</a>
            </td>
        </tr>
}
    </tbody>
</table>
<link href="~/css/BuscaMSG.css" rel="stylesheet" />
<script src="~/js/FiltrarMSG.js"></script>

HiperChat/WebChat/WebChat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Hiper Chat</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        
     

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">

                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img id="imglogo" src="~/css/hiper.png" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RespostaChats" asp-action="Index">Colocar aqui algo pras respostas</a>

                        </li>

                    </ul>

                </div>

            </div>

        </nav>
    </header>
 
        <div class="container">

            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>

        </div>

   


    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>